version: 2
updates:
  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    # Look for `go.mod` and `sum` files in the `root` directory
    directory: "/"
    # Check the go modules for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `ui` directory
    directory: "/ui"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `web` directory
    directory: "/ui/packages/app/web"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@parca/profile"
      - dependency-name: "@parca/client"
      - dependency-name: "@parca/dynamicsize"
      - dependency-name: "@parca/functions"
      - dependency-name: "@parca/icons"
      - dependency-name: "@parca/parser"
      - dependency-name: "@parca/store"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
