
[[constraint]]
  branch = "master"
  name = "github.com/alecthomas/template"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.6.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/pprof"

[[constraint]]
  name = "github.com/improbable-eng/thanos"
  version = "0.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/mwitkow/go-conntrack"

[[constraint]]
  name = "github.com/oklog/run"
  version = "1.0.0"

[[constraint]]
  name = "github.com/opentracing/opentracing-go"
  version = "1.0.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.9.2"

[[constraint]]
  name = "github.com/prometheus/common"
  version = "0.2.0"

[[constraint]]
  name = "github.com/prometheus/prometheus"
  version = "2.7.1"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true
