apiVersion: rbac.authorization.k8s.io/v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    labels:
      app.kubernetes.io/name: conprof
      app.kubernetes.io/version: v0.1.0-dev
    name: conprof
    namespace: conprof
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: conprof
  subjects:
  - kind: ServiceAccount
    name: conprof
    namespace: conprof
kind: RoleBindingList
