apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
    app.kubernetes.io/version: master-2020-04-24-66b9527
  name: conprof
  namespace: conprof
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    app.kubernetes.io/instance: conprof
    app.kubernetes.io/name: conprof
