---
apiVersion: v1
data:
  parca.yaml: |-
    "debug_info":
      "bucket":
        "cache":
          "config":
            "directory": "./tmp"
          "type": "FILESYSTEM"
        "config":
          "directory": "./tmp"
        "type": "FILESYSTEM"
kind: ConfigMap
metadata:
  name: parca-config
  namespace: parca
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca
    app.kubernetes.io/version: v0.0.1-alpha.2
  name: parca
  namespace: parca
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: observability
      app.kubernetes.io/instance: parca
      app.kubernetes.io/name: parca
  template:
    metadata:
      labels:
        app.kubernetes.io/component: observability
        app.kubernetes.io/instance: parca
        app.kubernetes.io/name: parca
        app.kubernetes.io/version: v0.0.1-alpha.2
    spec:
      containers:
      - args:
        - /parca
        - --config-path=/var/parca/parca.yaml
        - --log-level=info
        - --cors-allowed-origins=*
        image: ghcr.io/parca-dev/parca:v0.0.1-alpha.2
        livenessProbe:
          exec:
            command:
            - /grpc-health-probe
            - -v
            - -addr=:7070
          initialDelaySeconds: 5
        name: parca
        ports:
        - containerPort: 7070
          name: all
        readinessProbe:
          exec:
            command:
            - /grpc-health-probe
            - -v
            - -addr=:7070
          initialDelaySeconds: 10
        resources: {}
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /var/parca
          name: parca-config
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
      serviceAccountName: parca
      terminationGracePeriodSeconds: 120
      volumes:
      - configMap:
          name: parca-config
        name: parca-config
---
apiVersion: v1
kind: Namespace
metadata:
  name: parca
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca
    app.kubernetes.io/version: v0.0.1-alpha.2
  name: parca
  namespace: parca
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca
    app.kubernetes.io/version: v0.0.1-alpha.2
  name: parca
  namespace: parca
spec:
  ports:
  - name: all
    port: 7070
    targetPort: 7070
  selector:
    app.kubernetes.io/component: observability
    app.kubernetes.io/instance: parca
    app.kubernetes.io/name: parca
