name: buf-pr

on:
  pull_request:
    paths:
      - proto/**
      - buf.gen.yaml
      - buf.work.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1.1.1
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'proto'
      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'proto'
          # The 'main' branch of the GitHub repository that defines the module.
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1,subdir=proto'
