name: Go

on:
  push:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - .github/workflows/go-build-test.yml
  pull_request:
    branches: [ main ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - .github/workflows/go-build-test.yml

jobs:
  build-and-test-multi-arch:
    runs-on: ubuntu-latest
    name: Test on ${{ matrix.arch }}
    # Run steps on a matrix of 2 arch.
    strategy:
      matrix:
        arch:
          - x64
          # Names as per arch/ubuntu docker images.
          - arm64v8
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.18'
        check-latest: true
        cache: true

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'yarn'

    - name: Build
      if: ${{ matrix.arch == 'x64' }}
      run: |
        make build

    - name: Test
      if: ${{ matrix.arch == 'x64' }}
      run: |
        make go/test

    - name: Benchmark
      if: ${{ matrix.arch == 'x64' }}
      run: |
        make go/bench

    - name: Archive generated artifacts
      if: ${{ matrix.arch == 'x64' }}
      uses: actions/upload-artifact@v3
      with:
        name: parca-bin
        if-no-files-found: error
        path: |
          bin

    - name: 'Run ${{ matrix.arch }}'
      if: ${{ matrix.arch != 'x64' }}
      run: |
        # Install QEMU and it's dependencies.
        sudo apt-get install qemu binfmt-support qemu-user-static
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

        # Run platform specific based ubuntu image. Run it as a daemon in the background.
        # Sleep the container for 1 day so that it keeps running until
        # other steps are completed and the steps below can use the same container.
        ARCH=${{ matrix.arch }}
        # Ubuntu image name are different from arch image. So using this different variable.
        IMAGE=${{ matrix.arch }}
        if [ "$ARCH" == "arm64v8" ]; then
          ARCH="arm64"
        fi &&\
        docker run --name ${{ matrix.arch}}_ubuntu -d --platform linux/$ARCH -v `pwd`:/parca $IMAGE/ubuntu /bin/bash -c \
        'uname -m &&\
        sleep 1d'

    - name: 'Install packages on ${{ matrix.arch }}'
      if: ${{ matrix.arch != 'x64' }}
      run: |
        # Install necessary packages on the ${{ matrix.arch}}_ubuntu container which will be used
        # by below steps.
        docker exec -t ${{ matrix.arch}}_ubuntu /bin/bash -c \
        '# Update the container packages.
        apt-get update -y -q &&\
        apt-get upgrade -y -q &&\
        apt-get install -y -q wget make git file build-essential'

    - name: 'Setup Go on ${{ matrix.arch }}'
      if: ${{ matrix.arch != 'x64' }}
      run: |
        export RUNNER_ALLOW_RUNASROOT="1"
        # Install Golang, which will be used to build the code.
        docker exec -t ${{ matrix.arch}}_ubuntu /bin/bash -c \
        'ARCH=${{ matrix.arch }} && \
        if [ "$ARCH" == "arm64v8" ]; then
          ARCH="arm64"
        fi &&\
        wget https://dl.google.com/go/go1.18.2.linux-$ARCH.tar.gz &&\
        tar -C /usr/local/ -xzf go1.18.2.linux-$ARCH.tar.gz &&\
        export PATH=$PATH:/usr/local/go/bin && \
        go version'

    - name: 'Test on ${{ matrix.arch }}'
      if: ${{ matrix.arch != 'x64' }}
      run: |
        docker exec -t ${{ matrix.arch}}_ubuntu /bin/bash -c \
        '# Run Go Tests. This is a very slow operation on ARM container.
        export PATH=$PATH:/usr/local/go/bin &&\
        cd parca &&\
        mkdir -p ui/packages/app/web/build && \
        touch ui/packages/app/web/build/index.html && \
        go test -buildvcs=false -v ./...'
