name: proto-push

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/proto-push.yaml
      - proto/**
      - buf.gen.yaml
      - buf.work.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Set up Go
        uses: actions/setup-go@b22fbbc2921299758641fab08929b4ac52b32923 # tag=v3.2.0
        with:
          go-version-file: .go-version
          check-latest: true
          cache: true

      - uses: bufbuild/buf-setup-action@f6302b8734110a8557ffc49bb1b5ff7fae642400 # tag=v1.5.0

      - name: Format
        run: buf format --diff --exit-code

      - uses: bufbuild/buf-lint-action@15dd9902eef117bd24ff457b8818db21b44d34cb # tag=v1.0.0
        with:
          input: 'proto'

      - uses: bufbuild/buf-breaking-action@133a3d5b9140ea3a9f9ff5194039742c15e8da78 # tag=v1.0.0
        with:
          input: 'proto'
          # The 'main' branch of the GitHub repository that defines the module.
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1,subdir=proto'

      - uses: bufbuild/buf-push-action@1b31b985d86807e150c3bef5c4ea451db812acd2 # tag=v1.0.1
        with:
          input: 'proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
