name: proto-gen

on:
  pull_request:
    paths:
      - .github/workflows/proto-gen.yaml
      - proto/**
      - buf.gen.yaml
      - buf.work.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
          cache: true

      - uses: bufbuild/buf-setup-action@v1.4.0
        with:
          version: 1.5.0

      - name: Generate
        run:
          make proto/generate && git diff --exit-code
