name: proto-push

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/proto-push.yaml
      - proto/**
      - buf.gen.yaml
      - buf.work.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.18

      - uses: bufbuild/buf-setup-action@v1.3.1
        with:
          version: 1.3.1

      - name: Format
        run: buf format --diff --exit-code

      - uses: bufbuild/buf-lint-action@v1
        with:
          input: 'proto'

      - uses: bufbuild/buf-breaking-action@v1
        with:
          input: 'proto'
          # The 'main' branch of the GitHub repository that defines the module.
          against: 'https://github.com/${GITHUB_REPOSITORY}.git#branch=main,ref=HEAD~1,subdir=proto'

      - uses: bufbuild/buf-push-action@v1
        with:
          input: 'proto'
          buf_token: ${{ secrets.BUF_TOKEN }}
